version: "3.8"

services:
  # database:
  #   image: mysql
  #   restart: always
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: root
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./.mysql:/var/lib/mysql
  #   ports:
  #     - "3306:3306"
  #   container_name: project-db

  project:
    build: .
    ports:
      - "8080:8080"
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/api/node_modules
      - /app/packages/web/node_modules
    container_name: sabia-platform
